### ISSUE TITLE
coronal view

### ISSUE THREAD

**Issue by arshamkhodajoo** [rii-mango/NIFTI-Reader-JS#18]
Hi, thanks for this handy library
this is not really an issue, but I have struggle getting coronal view instead of axial for brain images.
I have brain MRI images in axial view with dimention of `(240, 240, 155)` and [this example](https://github.com/rii-mango/NIFTI-Reader-JS/blob/master/tests/canvas.html) successfuly draws images on screen

but now I'm looking for coronal view like [this image](https://www.researchgate.net/profile/Murali-Erasa/publication/340046221/figure/fig1/AS:870973993652224@1584667790173/Different-angle-Views-of-the-Brain.jpg) which happens when treat columns as slices and slices as column : 

`(rows, column, slices)` to `(rows, slices, column)`

I would appreciate your guidance.

**Comment by znshje** [comment]
Hi,

maybe you can try this library: [https://github.com/scijs/ndarray](https://github.com/scijs/ndarray), which operates like NumPy. Since the image data is stored in a `Uin8Array`, you can easily reshape the data using `ndarray` and call `array.pick()` to select the columns you want.

This is a brief sample:
```javascript
    let header = nifti.readHeader(binaryData)   // binaryData is an arrayBuffer you download or read locally
    let dims = header.dims
    let stride = [1, dims[1], dims[1] * dims[2]]
    let array = ndarray(imageData, [dims[1], dims[2], dims[3]], stride).step(1, 1, -1)   // imageData is a TypedArray, see the docs

    const getImage = (dim, slice) => {
        let image
        if (dim === 1) {
            image = array.pick(slice, null, null)
        } else if (dim === 2) {
            image = array.pick(null, slice, null)
        } else if (dim === 3) {
            image = array.pick(null, null, header.dims[3] - slice - 1)
        }
        return image
    }
```

Thus, you can get images from coronal view as `getImage(2, SLICE)`.

Hope this will help!

**Comment by neurolabusc** [comment]
If you want to display axial, coronal and sagittal views from a 3D volume it is easiest to use WebGL2. This version introduced 3D textures, which are like 3D bitmaps (e.g. 2D bitmaps are pixel based, 3D are voxel based). This means that you do not have to send data between the CPU and GPU for each slice and every frame, rather the entire 3D array is in the GPU memory and the shader samples the desired plane.

You can see this in [NiiVue](https://niivue.github.io/niivue/) where the shader uniform [axCorSag](https://github.com/niivue/niivue/blob/2d88c525628d38427efae9a9991d73c07067089d/src/shader-srcs.js#L394) selects between axial, coronal and sagittal slices. Since Texture dimensions are always sampled from 0..1, you would choose an axial slice would be [0,0,z],[1,0,z],[1,1,z],[0,1,z], a coronal slice would be [0,y,0],[1,y,0],[1,y,1],[0,y,1] and the sagittal slice would be  [x,0,0],[x,1,0],[x,1,1],[x,0,1] assuming your voxels are in RAS orientation (NiiVue includes code that will swizzle voxel order to RAS).

**Comment by Hermanboi97** [comment]
Hi [znshje](https://github.com/znshje), 
I'm not familiar with the ndarray library, and I was wondering how you would put the ndarray from the getImage function into the image data, as it is done in the [example](https://github.com/rii-mango/NIFTI-Reader-JS/blob/master/tests/canvas.html).

**Comment by znshje** [comment]
Hi @Hermanboi97 , the `ndarray` takes a `TypedArray` as the first parameter. The `imageData` in my code is identical to the `typedData` in the example.

**Comment by neurolabusc** [comment]
Closing this issue based on solution from @znshje
