### ISSUE TITLE
Open nifti files with corrupted extension setting

### ISSUE THREAD

**Issue by korbinian90** [rii-mango/NIFTI-Reader-JS#35]
There are some pipelines that produce nifti files with an incoherent header that still can be opened with other viewers (e.g. mricro), but throw an error here.

The problem in the corrupted nifti files seems to be that the extensionFlag[0] (byte 348 + 1) is set, but there is no extension to load.

(I had users of niivue-vscode reporting that problem, documented here: https://github.com/niivue/niivue-vscode/issues/32)

**Comment by neurolabusc** [comment]
@korbinian90 this suggests that the tool that created the NIfTI header did not initialize all bytes of the header to zero before writing. While we should certainly handle this situation, it also suggests a buffer-overflow vulnerability. In other words, some bytes of the header may contain private data that was stored in memory. 

A clear example of this issue was seen in previous versions of the Siemens V* DICOM writing, where the private CSA header was not zeroed. Users could remove all the privacy related tags from a DICOM header, but private information was preserved and hidden in the CSA header. I did see examples of Siemens data where the patient name was accidentally hidden in CSA header. In theory, the benefit of the NIfTI header to the DICOM is it is much smaller and more explicit, so there are not many bytes that are not required to be allocated. 

Therefore, I would be very concerned with your source data: do make sure that your tools [explicitly zero the NIfTI header](https://github.com/rordenlab/dcm2niix/blob/fe2f26005109f396a4f828aa438241f73fc25fe8/console/nii_dicom.cpp#L1588C22-L1588C36) to ensure that bytes devoted to null-terminated strings do not leak private data.

**Comment by korbinian90** [comment]
Oh, that is good to know. I will have a closer look where the data comes from.

**Comment by hanayik** [comment]
closed by #37
