### ISSUE TITLE
How to convert the nifti data into canvas data.

### ISSUE THREAD

**Issue by George35mk** [rii-mango/NIFTI-Reader-JS#6]
I m trying to convert the data from the `niftiImage = nifti.readImage(niftiHeader, data);`

in to some useful format where I can manipulate the data.

what I want on the final result is to have 3 canvas elements and for each of them to show the data in 3 dimension

example:
```
<canvas id="show-x-data"></canvas>
<canvas id="show-y-data"></canvas>
<canvas id="show-z-data"></canvas>
```

Ok I have an ArrayBuffer if I call:  `niftiImage = nifti.readImage(niftiHeader, data);`

but I dont know what to do with this data. how should I know on which part is for x dimension or y or z?

let's say I have a canvas element and I want to render the 25th image on x-axis how I can do this. 
I think the **NIFTI-Reader-JS** should show some documentation on this without redirecting the users in the PAPAYA repository,

I was trying to read the `https://github.com/rii-mango/Papaya/blob/master/src/js/viewer/screenslice.js` but there is so much noise, so I can focus how they extract the data and render the data on each axis.

Can, someone show me how to render **a single image** on x axis, one on y axis and one more on z axis.

Thanks.

**Comment by martinezmj** [comment]
Hi, sorry for the late reply.  I'm a little confused by what you're referring to with "x/y/z-axis".  If we are talking about a single volume of data, then most likely you'd want to show a single canvas, which would draw a slice from that volume.  That is, the data is 3-D, composed of say 100 slices and you would draw a single 2-D slice on that canvas.

The niftiImage is just one long array of numbers.  It's ordered by column, then row, then slice.  You'll need to get what the number of columns, rows and slices is from the nifti header.  If it's say columns=50, rows=60, slices=100, then the first 50 number will be the first row.  The first 50 * 60 numbers will be the first slice.

Converting it into something you can draw on the canvas is additional work, since the number can be in any range -- and to draw to the screen, it needs to be normalized to screen range values.

Hope this helps a little.  Let me know if you have additional questions and I can try to help more.

**Comment by rii-mango** [comment]
I've posted an example of how to read and draw a nifti to a canvas: https://github.com/rii-mango/NIFTI-Reader-JS/blob/master/tests/canvas.html

**Comment by rii-mango** [comment]
Same as issue #5 , closing.

**Comment by George35mk** [comment]
> Hi, sorry for the late reply. I'm a little confused by what you're referring to with "x/y/z-axis". If we are talking about a single volume of data, then most likely you'd want to show a single canvas, which would draw a slice from that volume. That is, the data is 3-D, composed of say 100 slices and you would draw a single 2-D slice on that canvas.
> 
> The niftiImage is just one long array of numbers. It's ordered by column, then row, then slice. You'll need to get what the number of columns, rows and slices is from the nifti header. If it's say columns=50, rows=60, slices=100, then the first 50 number will be the first row. The first 50 * 60 numbers will be the first slice.
> 
> Converting it into something you can draw on the canvas is additional work, since the number can be in any range -- and to draw to the screen, it needs to be normalized to screen range values. Briefly, if you know the range of data (also which you can get from the header), then you can normalize it to a 0-255 range.
> 
> Hope this helps a little. Let me know if you have additional questions and I can try to help more.

Hi @martinezmj I have one more question I hope you can help me

I finally manage to draw the canvas and get the slices, based on an example from here https://github.com/rii-mango/NIFTI-Reader-JS/blob/master/tests/canvas.html but I want to get the `saggital` and `coronal` slices as well. any help on this it will help me

Thank you.
