### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by kmannislands** [rii-mango/NIFTI-Reader-JS#8]
Any interest in a PR with a type declaration file for this library?

Have it about 70% typed locally for a project and would be happy to contribute it

**Comment by MauricePasternak** [comment]
That would be appreciated if you still have it around.

**Comment by kmannislands** [comment]
@martinezmj I'd almost prefer just to rewrite it in typescript... would you consider such a drastic change? Or should that be a fork?

**Comment by neurolabusc** [comment]
@kmannislands, @martinezmj has moved to industry. However, I do think that TypeScript would be a nice feature. @hanayik is now the active maintainer. My sense is it would be better to keep a single repository rather than a fork where it is harder to keep support new features in multiple sources. If you are still interested, I suggest you rewrite to typescript and make a pull request. I think @cdrake would be a thorough and enthusiastic reviewer.

**Comment by kmannislands** [comment]
@neurolabusc Okay cool, sounds good. Fully converting to typescript will require a non-trivial amount of code/tooling change so best to split this up into a few PRs, probably into a feature branch on the `NIFTI-reader-JS` side.

**Comment by kmannislands** [comment]
Have a few branches out. Other than tooling, the main conversion to `ts` is here:

https://github.com/kmannislands/NIFTI-Reader-JS/pull/2
